export const WEBHOOK_EVENTS = [
  { id: 1, name: 'issueCreated', description: 'Issue Created' },
  { id: 2, name: 'issueUpdated', description: 'Issue Updated' },
  { id: 3, name: 'issueCommented', description: 'Issue Commented' },
  { id: 4, name: 'issueDeleted', description: 'Issue Deleted' },
  { id: 5, name: 'wikiCreated', description: 'Wiki Created' },
  { id: 6, name: 'wikiUpdated', description: 'Wiki Updated' },
  { id: 7, name: 'wikiDeleted', description: 'Wiki Deleted' },
  { id: 8, name: 'fileAdded', description: 'File Added' },
  { id: 9, name: 'fileUpdated', description: 'File Updated' },
  { id: 10, name: 'fileDeleted', description: 'File Deleted' },
  { id: 11, name: 'svnCommitted', description: 'SVN Committed' },
  { id: 12, name: 'gitPushed', description: 'Git Pushed' },
  { id: 13, name: 'gitRepositoryCreated', description: 'Git Repository Created' },
  { id: 14, name: 'issueMultiUpdated', description: 'Issue Multi Updated' },
  { id: 15, name: 'projectUserAdded', description: 'Project User Added' },
  { id: 16, name: 'projectUserDeleted', description: 'Project User Deleted' },
  { id: 17, name: 'commentNotificationAdded', description: 'Comment Notification Added' },
  { id: 18, name: 'pullRequestAdded', description: 'Pull Request Added' },
  { id: 19, name: 'pullRequestUpdated', description: 'Pull Request Updated' },
  { id: 20, name: 'commentAddedOnPullRequest', description: 'Comment Added on Pull Request' },
  { id: 21, name: 'pullRequestDeleted', description: 'Pull Request Deleted' },
  { id: 22, name: 'milestoneCreated', description: 'Milestone Created' },
  { id: 23, name: 'milestoneUpdated', description: 'Milestone Updated' },
  { id: 24, name: 'milestoneDeleted', description: 'Milestone Deleted' },
  { id: 25, name: 'projectGroupAdded', description: 'Project Group Added' },
  { id: 26, name: 'projectGroupDeleted', description: 'Project Group Deleted' },
  { id: 36, name: 'documentCreated', description: 'Document Created' },
  { id: 37, name: 'documentDeleted', description: 'Document Deleted' },
  { id: 38, name: 'documentTitleUpdated', description: 'Document Title Updated' },
  { id: 39, name: 'documentRevisionUpdated', description: 'Document Revision Updated' },
  { id: 40, name: 'documentCommented', description: 'Document Commented' },
  { id: 41, name: 'documentCommentUpdated', description: 'Document Comment Updated' },
  { id: 42, name: 'documentCommentDeleted', description: 'Document Comment Deleted' },
  { id: 43, name: 'documentCommentReplyCreated', description: 'Document Comment Reply Created' },
  { id: 44, name: 'documentCommentReplyUpdated', description: 'Document Comment Reply Updated' },
  { id: 45, name: 'documentCommentReplyDeleted', description: 'Document Comment Reply Deleted' },
  { id: 46, name: 'documentAttachmentAdded', description: 'Document Attachment Added' },
  { id: 48, name: 'documentMultiCreated', description: 'Document Multi Created' },
  { id: 49, name: 'documentMentioned', description: 'Document Mentioned' },
] as const

export type WebhookEventName = (typeof WEBHOOK_EVENTS)[number]['name']

export type WebhookEvent = WebhookEventName | number
